[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_dapp = "G6EWd6ucYtZZmo6pEfGkFzkkWVVQDxd98TcVMvRWXeBH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '/home/patel96/config/validator.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
